# Generated by Django 3.1 on 2020-09-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(default='Not mentioned', max_length=50),
        ),
    ]
