# Generated by Django 3.1 on 2020-09-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
    ]
