# Generated by Django 3.1.2 on 2020-10-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_delete_book'),
        ('users', '0004_auto_20201021_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
    ]
