# Generated by Django 3.1 on 2020-10-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201010_1156'),
        ('users', '0004_remove_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ManyToManyField(to='main.School'),
        ),
    ]
