# Generated by Django 3.1 on 2020-10-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201012_1838'),
        ('users', '0005_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(to='main.Class'),
        ),
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.ManyToManyField(to='main.Semester'),
        ),
    ]
