# Generated by Django 3.1 on 2020-10-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201012_1838'),
        ('users', '0006_auto_20201014_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='main.Class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(to='main.Course'),
        ),
    ]
