# Generated by Django 3.1 on 2020-10-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20201015_1122'),
        ('users', '0007_auto_20201014_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(limit_choices_to=1, to='main.Class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(limit_choices_to=1, to='main.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ManyToManyField(limit_choices_to=1, to='main.School'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.ManyToManyField(limit_choices_to=1, to='main.Semester'),
        ),
    ]
