# Generated by Django 3.1 on 2020-10-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20201015_1122'),
        ('users', '0008_auto_20201017_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='main.Class'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.ManyToManyField(to='main.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.ManyToManyField(to='main.School'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.ManyToManyField(to='main.Semester'),
        ),
    ]
