# Generated by Django 3.1 on 2020-09-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.ManyToManyField(to='main.Schools'),
        ),
        migrations.AddField(
            model_name='post',
            name='semester',
            field=models.ManyToManyField(to='main.Semesters'),
        ),
    ]
