# Generated by Django 3.1.2 on 2020-11-05 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_user',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report_user',
            name='short_explanation',
            field=models.CharField(max_length=30),
        ),
    ]
