# Generated by Django 3.1 on 2020-09-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200922_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schools',
            new_name='School',
        ),
        migrations.RenameModel(
            old_name='Semesters',
            new_name='Semester',
        ),
    ]
