# Generated by Django 3.1.3 on 2020-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201104_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_user',
            name='reported',
        ),
        migrations.AddField(
            model_name='report_user',
            name='url_report',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
