# Generated by Django 3.1 on 2020-09-22 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200922_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='semester',
        ),
        migrations.AddField(
            model_name='post',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.IntegerField(),
        ),
    ]
