# Generated by Django 3.1.3 on 2020-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201111_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_user',
            name='reported',
        ),
        migrations.AlterField(
            model_name='report_user',
            name='url_report',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
