# Generated by Django 3.1 on 2020-09-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200922_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='name',
            new_name='semester_number',
        ),
    ]
