# Generated by Django 3.1 on 2020-09-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200922_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester_number',
            new_name='semester',
        ),
    ]
