# Generated by Django 3.1 on 2020-09-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200922_2044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='school',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='school',
            name='slug',
        ),
    ]
