# Generated by Django 3.1 on 2020-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isbn',
            field=models.IntegerField(default=0),
        ),
    ]
