# Generated by Django 3.1.1 on 2020-09-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_books_class_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.AddField(
            model_name='class',
            name='books',
            field=models.ManyToManyField(to='main.Book'),
        ),
        migrations.AddField(
            model_name='course',
            name='all_classes',
            field=models.ManyToManyField(to='main.Class'),
        ),
        migrations.AddField(
            model_name='school',
            name='courses',
            field=models.ManyToManyField(to='main.Course'),
        ),
    ]
