# Generated by Django 3.1.1 on 2020-09-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200926_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AddField(
            model_name='class',
            name='choices',
            field=models.CharField(choices=[('Math_Seneca_1', 'Math_Seneca_1'), ('English_UFT_1', 'English_UFT_1'), ('Geo_York_2', 'Geo_York_2'), ('Economics_Cent_3', 'Economics_Cent_3')], max_length=200, null=True),
        ),
    ]
