# Generated by Django 3.1.1 on 2020-09-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200926_2338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='4- Books',
        ),
        migrations.AlterModelTable(
            name='class',
            table='1- Class',
        ),
        migrations.AlterModelTable(
            name='course',
            table='2- Course',
        ),
        migrations.AlterModelTable(
            name='school',
            table='3- School',
        ),
    ]
