# Generated by Django 3.1.1 on 2020-09-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200926_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='choices',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
