# Generated by Django 3.1.1 on 2020-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200926_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='choices_course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='courses',
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ManyToManyField(to='main.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ManyToManyField(to='main.School'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ManyToManyField(to='main.Semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='not declared', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(default='not declared', max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='not declared', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='not declared', max_length=200),
        ),
        migrations.AlterModelTable(
            name='book',
            table='5- Books',
        ),
        migrations.AlterModelTable(
            name='class',
            table='4- Class',
        ),
        migrations.AlterModelTable(
            name='course',
            table='3- Course',
        ),
        migrations.AlterModelTable(
            name='school',
            table='1- School',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='2- Semester',
        ),
    ]
