# Generated by Django 3.1 on 2020-10-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201002_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='semester',
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ManyToManyField(to='main.Semester'),
        ),
    ]
