# Generated by Django 3.1 on 2020-10-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201002_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='schools',
            field=models.ManyToManyField(to='main.School'),
        ),
    ]
