# Generated by Django 3.1 on 2020-10-02 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_book_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
