# Generated by Django 3.1 on 2020-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20201005_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='default.jpg', upload_to='post_image'),
        ),
    ]
