# Generated by Django 3.1 on 2020-10-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_post_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='classes',
            field=models.ManyToManyField(to='main.Class'),
        ),
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
