# Generated by Django 3.1 on 2020-10-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201015_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterModelTable(
            name='class',
            table=None,
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
        migrations.AlterModelTable(
            name='semester',
            table=None,
        ),
    ]
