# Generated by Django 3.1.2 on 2020-10-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_course_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
